### ISSUE TITLE
Use not freezed dependencies

### ISSUE THREAD

**Issue by anton44eg** [ConsenSys/ethjsonrpc#12]
Now ethjsonrpc strictly requires **requests==2.9.1**.  I may cause problems for some projects. Do someone test it with older/newer  **requests**?

**Comment by maurycyp** [comment]
@anton44eg I've tested with older versions of **requests** but not yet 2.10.0 .  I know you're supposed to be less strict about versions (e.g. `requests>=2`) but in my experience I've been bitten by so many problems caused by dependency version changes that I prefer to pin the exact version.

I plan to give the **ethjsonrpc**'s libraries another version bump in the near future.
